### ISSUE TITLE
Optionally make jemallocator register as a #[global_allocator]

### ISSUE THREAD

**Issue by SimonSapin** [alexcrichton/jemallocator#88]
Following up on https://internals.rust-lang.org/t/jemalloc-was-just-removed-from-the-standard-library/8759/10, it makes sense to me to add two Cargo features to this crate:

* `global_allocator_on_tested_platforms`: define the `#[global_allocator]` with a `cfg` that only applies to targets this repository has CI for.
* `global_allocator`: same, but unconditional. It *might* work on an untested platform.

CC @gnzlbg @sfackler @alexcrichton

**Comment by SimonSapin** [comment]
Hmm, I just realized that for the conditional one we probably don’t want to link to `jemalloc-sys` on untested platforms, so it might need to be a separate crate rather than a feature of `jemallocator`.

**Comment by gnzlbg** [comment]
I think that we can put the `global_allocator` (unconditional) in `jemallocator`, but I think it might be worth it to do the "`global_allocator_on_supported_platforms` on a different crate, so that we only include `jemallocator` (and therefore `jemalloc-sys`) in those platforms in which it is guaranteed to work, and the crate is "empty" otherwise. It should be possible to bolt this logic onto `jemallocator` itself, but that will be messy.

**Comment by SimonSapin** [comment]
This is fixed by https://github.com/alexcrichton/jemallocator/pull/90
